### ISSUE TITLE
The LabelPositions.TOP does not work.

### ISSUE THREAD

**Issue by EircYangQM** [barnhill/barcode-java#18]
The line 914 in barcode.java. 

`if ((getLabelPosition().ordinal() & Labels.LabelPositions.TOP.ordinal()) > 0)`

 Labels.LabelPositions.TOP.ordinal() is 0, So it is always 0. Maybe we just check the enum not enum's value.

**Comment by barnhill** [comment]
Care to create a PR?

**Comment by EircYangQM** [comment]
I add the PR. please check this.

**Comment by barnhill** [comment]
This was addressed in https://github.com/barnhill/barcode-java/pull/19.  Closing.
