### ISSUE TITLE
Maven dependency

### ISSUE THREAD

**Issue by DenisMakovskyi** [barnhill/barcode-java#2]
Maven dependency is not available.
<dependency>
    <groupId>com.pnuema.java</groupId>
    <artifactId>barcode</artifactId>
    <version>1.1</version>
</dependency>
Dependecy com.pnuema.java.barcode:1.1 not found

**Comment by barnhill** [comment]
https://jcenter.bintray.com/com/pnuema/java/barcode/1.1/

**Comment by barnhill** [comment]
Are you trying to get it from mavenCentral instead of jcenter?

**Comment by barnhill** [comment]
@DenisMakovskyi  it should be available in jcenter and the maven central repo now.  Closing.
