### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by we-sell-bags** [barnhill/barcode-java#21]
This code just produces a solid
barcode with no text, it is not teh same as the sample image.

`Barcode barcode = new Barcode();
Image img = barcode.encode(BarcodeLib.TYPE.UPCA, "038000356216");`

**Comment by barnhill** [comment]
```
Barcode barcode = new Barcode(); 
barcode.IncludeLabel = true;
Image img = barcode.encode(BarcodeLib.TYPE.UPCA, "038000356216");
```
