### ISSUE TITLE
Lib can't be pulled from Maven since 2.2

### ISSUE THREAD

**Issue by zzrough** [barnhill/barcode-java#26]
hello,

Thanks for the library, I'm using it from quite a long time and it works nice!

I was using the 1.x branch and wanted to switch to the latest (2.6.1) but I see the artifacts are hosed since 2.2. I get the error:
`The following artifacts could not be resolved: com.pnuema.java:barcode:jar:2.6.1 (absent)` when using the dependency example shown in the README.

If I check on mvnrepository, it's ok in 2.1:
![image](https://github.com/barnhill/barcode-java/assets/490496/0170f178-9417-4c91-be37-ec28e28074b0)
![image](https://github.com/barnhill/barcode-java/assets/490496/89767483-37f4-4852-84d2-8fefe6cb08f0)

But in 2.2, it's not published the same we see a -jar.jar:
![image](https://github.com/barnhill/barcode-java/assets/490496/086aeb83-2525-44cb-a5e9-b62c7f253468)
![image](https://github.com/barnhill/barcode-java/assets/490496/4345eb2e-b8ec-4723-b375-818daad42745)

I see a commit mentioning a classifier change which is certainly the -jar is all about.
I did not add the dependency in a fancy way but it does not see to work anymore from 2.2 onwards.

best regards,
--Stef

**Comment by zzrough** [comment]
(I had to add <classifier>jar</classifier> in the dependency node, but it's the only lib I need to do this, I wonder why)

**Comment by barnhill** [comment]
What the ... Why is it tacking on a funky name.  I'll look at this

**Comment by barnhill** [comment]
Just published 2.6.2 that should have the archive name corrected.  It takes some time to sync with maven central then Ive got my personal project that uses it and Ill try to pull it in there to make sure the dependency resolution works correctly.

**Comment by barnhill** [comment]
Looks like its already available.  I just built my project and pulled that in successfully.  Let me know if this works for you to switch to version 2.6.2

![Screenshot 2024-04-07 at 10 48 39 AM](https://github.com/barnhill/barcode-java/assets/3878158/69672901-7d51-44dc-8dda-1f112c66e27e)

**Comment by zzrough** [comment]
hey I answered just after your comment from email but I see my reply was not sent over github or it does not work anymore to reply by email?
```
it works great! so fast to fix it!
thanks a lot!
--Stef
```

But, when running in UAT I spot we had many new librairies:
```
*** kotlin-android-extensions-1.9.22.jar ***
*** kotlin-build-tools-api-1.9.22.jar ***
*** kotlin-compiler-embeddable-1.9.22.jar ***
*** kotlin-compiler-runner-1.9.22.jar ***
*** kotlin-daemon-client-1.9.22.jar ***
*** kotlin-daemon-embeddable-1.9.22.jar ***
*** kotlin-gradle-plugin-1.9.22.jar ***
*** kotlin-gradle-plugin-annotations-1.9.22.jar ***
*** kotlin-gradle-plugin-api-1.9.22.jar ***
*** kotlin-gradle-plugin-idea-1.9.22.jar ***
*** kotlin-gradle-plugin-idea-proto-1.9.22.jar ***
*** kotlin-gradle-plugin-model-1.9.22.jar ***
*** kotlin-klib-commonizer-api-1.9.22.jar ***
*** kotlin-native-utils-1.9.22.jar ***
*** kotlin-project-model-1.9.22.jar ***
*** kotlin-scripting-common-1.9.22.jar ***
*** kotlin-scripting-compiler-embeddable-1.9.22.jar ***
*** kotlin-scripting-compiler-impl-embeddable-1.9.22.jar ***
*** kotlin-scripting-jvm-1.9.22.jar ***
*** kotlin-stdlib-1.9.22.jar ***
*** kotlin-tooling-core-1.9.22.jar ***
*** kotlin-util-io-1.9.22.jar ***
*** kotlin-util-klib-1.9.22.jar ***
*** kotlinx-coroutines-core-jvm-1.7.3.jar ***
```

I see the project brings kotlin-stdlib in compile scope but I don't see any use in the source code?
The rest is runtime but pulled of transitively so the barcode project adds many libraries.

--Stef

**Comment by barnhill** [comment]
Probably this line in the Gradle config

https://github.com/barnhill/barcode-java/blob/master/build.gradle.kts#L24

**Comment by barnhill** [comment]
This project does use dokka for javadoc generation and that uses kotlin but the actual project doesnt.  

Even removing this doesnt change the size of the jar.

<img width="404" alt="Screenshot 2024-04-11 at 10 59 27 PM" src="https://github.com/barnhill/barcode-java/assets/3878158/f94c84db-df78-4b83-8f86-6ed6f067abe4">

**Comment by barnhill** [comment]
I did remove those and published 2.6.3 tonight to see if that helps you all.  Please let me know if removing those dependencies in this commit helped.

https://github.com/barnhill/barcode-java/compare/2.6.2...2.6.3

**Comment by zzrough** [comment]
thanks, I tested with 2.6.3 the change is very different, my app total distribution size:
* with 1.16:   92MB
* with 2.6.2: 167MB
* with 2.6.3:  95MB

I see indeed the dokka deps pulling deps a bit:
![image](https://github.com/barnhill/barcode-java/assets/490496/8c608f79-4aa6-40a4-8e79-32e06e634b75)

I received the following extra transitive deps:
* annotations-23.0.0.jar
* dokka-core-1.9.20.jar
* dokka-gradle-plugin-1.9.20.jar
* jackson-module-kotlin-2.16.1.jar
* kotlinx-coroutines-core-jvm-1.7.3.jar

I did not practice Gradle for a long time, but it seems to me this should be a plugin (in plugins section), not a project dependency (in dependency section)? https://kotlin.github.io/dokka/1.4.0/user_guide/gradle/usage/

**Comment by barnhill** [comment]
But I see it's way down from the previous.

**Comment by zzrough** [comment]
yes it's better but still brings a couple of libs from dokka... I'll ignore them in my project for the time being :+1: 
thanks for your help

**Comment by barnhill** [comment]
Going to close this since the artifact is available via maven again
