### ISSUE TITLE
Pharmacode with values 3,4,5,7,8,9 doesn't encode correctly

### ISSUE THREAD

**Issue by robwjwilson** [barnhill/barcode-java#8]
When generating a pharmacode barcode with the value 3 or 4 or 5 then I only seem to get a solid black box, i.e. a single barcode line that fills the area I specify.

When generating a pharmacode barcode with the value 6, I correctly get a wide bar, space and wide bar, however, generating with 7 or 8 or 9 also gives the same barcode as when using 6 as the value.

**Comment by barnhill** [comment]
Is it a single digit barcode?

**Comment by robwjwilson** [comment]
Hello. Yes, that's right.  Any of those values on their own don't produce the correct encoding for the barcode.  If I enter just 3 for example, then I just get a solid black box

**Comment by barnhill** [comment]
Yep I have confirmed this is a bug.  I just have to find it now.

**Comment by barnhill** [comment]
Found the bug and Ill push up a fix and close this out as soon as I can.

**Comment by barnhill** [comment]
Addressed with https://github.com/barnhill/barcode-java/commit/66d40c0bef1dfa52b4cb294d85cb9b22a111ef69
