### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by MedouneSGB** [barnhill/barcode-java#9]
Hi Brad 
I got some error when trying to run the project 
Is there some settings to make before using it?

![image](https://user-images.githubusercontent.com/40875400/116500985-41ac2800-a89f-11eb-8ba2-5713f0b07c93.png)

**Comment by barnhill** [comment]
Hum that's used in CI for uploading to maven central.  The binaries are already compiled and available in the central repo.

**Comment by barnhill** [comment]
Did you use `implementation 'com.pnuema.java:barcode:1.11'` in your build.gradle to pull in this dependency?

**Comment by MedouneSGB** [comment]
Hey @barnhill
Still can't open the project  
What are the steps to test it?

**Comment by barnhill** [comment]
I'm using intellij ... Not sure what to do in eclipse

**Comment by MedouneSGB** [comment]
I use Netbeans

**Comment by MedouneSGB** [comment]
![image](https://user-images.githubusercontent.com/40875400/163739795-d3da4afb-26c3-44c0-b7ca-ad2ec2d6af0b.png)
Getting this with intellij

**Comment by MedouneSGB** [comment]
Btw I created a little Barcode software.
https://github.com/MedouneSGB/Barcodor

**Comment by barnhill** [comment]
Those params are only used to upload it to maven central.  To use this in a project you can just pull it from the central repository but if you want to build it you can just define those in your gradle.properties file or as env variables.  It wont let you upload it to the central repo though which is kinda the point of not including those :)
